### ISSUE TITLE
How to get the PALAU grid nc file?

### ISSUE THREAD

**Issue by wubizhi** [ESMG/pyroms#36]
hi,

when i tried to run the Palau_HYCOM in examples folder,i find these is not the definition for the "PALAU1",
but it is used in the "make_remap_weights_file.py"
<img width="401" alt="屏幕快照 2021-05-27 下午4 39 32" src="https://user-images.githubusercontent.com/7642260/119794471-21a56e00-bf0a-11eb-8648-56103fe77c29.png">

but i can't find the definition in the gridid.txt .

![屏幕快照 2021-05-27 下午4 41 23](https://user-images.githubusercontent.com/7642260/119794810-721ccb80-bf0a-11eb-9013-9fd14bb9c977.png)

can anyone help me how to get the palau nc file and the definition cell?

Thanks!

**Comment by kshedstrom** [comment]
The Palau chunk (one of them) is:
```
id      = PALAU1
name    = PALAU1
grdfile = /import/AKWATERS/kshedstrom/gridpak/Palau/grid_Palau_1.nc
N       = 50
grdtype = roms
Vtrans  = 4 
theta_s = 7 
theta_b = 2 
Tcline  = 250 
```
I have a collection of Palau grids and a colleague has since made other, newer ones. I'm afraid we don't have a standard way to get them to you any more. But really, it's a straightforward rectangular grid near the equator. Do you have a grid of your own for your region of interest?
